server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  application:
    name: apiGateWay
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: service
          uri: http://localhost:8087
          predicates:
            - Host=*
          filters:
            - AddRequestHeader=x-request-service, request
            - AddResponseHeader=x-request-service, response
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
  instance:
    instance-id: gateway-8086
    appname: gatewayCenter
info:
  app:
    name: gatewayCenter